---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-demo-cyisme-top-v1-inplaceupdate
  failurePolicy: Fail
  name: minplaceupdate.kb.io
  rules:
  - apiGroups:
    - apps.demo.cyisme.top
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inplaceupdates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-demo-cyisme-top-v1-inplaceupdate
  failurePolicy: Fail
  name: vinplaceupdate.kb.io
  rules:
  - apiGroups:
    - apps.demo.cyisme.top
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - inplaceupdates
  sideEffects: None
