apiVersion: apps.demo.cyisme.top/v1
kind: InplaceUpdate
metadata:
  labels:
    app.kubernetes.io/name: inplaceupdate
    app.kubernetes.io/instance: inplaceupdate-sample
    app.kubernetes.io/part-of: program
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: program
  name: inplaceupdate-sample
spec:
  targetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: nginx
  containers:
    - name: nginx
      image: nginx:v1.25.6
