---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.demo.cyisme.top
  resources:
  - inplaceupdates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.demo.cyisme.top
  resources:
  - inplaceupdates/finalizers
  verbs:
  - update
- apiGroups:
  - apps.demo.cyisme.top
  resources:
  - inplaceupdates/status
  verbs:
  - get
  - patch
  - update
